# Theme settings
doks:
    baseurl:
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    # SEO settings
    title: InchanBaek Note - AI, Architecture & Technology
    description: Inchan Baek's blog on AI, architecture, and technology research and projects.
    author: Inchan Baek
    twitter:
        username: 
        card: summary
    header:
        logo:
            text: InchanBaek Note
            image:
        nav:
            # - item_name: Item 1
            #   item_url: '#'
            # - item_name: Item 2
            #   item_url: '#'
            # - item_name: Item 3
            #   item_url: '#'
    footer:
        content:
            logo:
                text: InchanBaek Note
                image:
            copyright: Copyright &copy; 2017. - InchanBaek Note <br>All rights reserved.
        social_list:
            - network_name: linkedin
              profile_url: 'https://www.linkedin.com/in/inchan-baek-728197265/'
            - network_name: instagram
              profile_url: 'https://www.instagram.com/in_chanchan/'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/@icb6048'
    google_analytics:
        tracking_code: GTM-MM5MVC48 # Google Tag Manager ID
    # SEO Plugin settings
    url: https://inchanbaek.com # Replace with your actual domain
    comments:
        disqus_forum_shortname: inchanbaeknote # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  auto_ids: true

# Mermaid diagram support
mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'
